### ISSUE TITLE
Found Sensitive Information

### ISSUE THREAD

**Issue by qoharu** [EggyBond/storas-backend#1]
Please do remove this repository or make the repository private, we found that you expose sensitive information to the worldwide (https://github.com/EggyBond/storas-backend/tree/master/config), Including our Firebase Credentials. Meanwhile, we already remove all our cloud projects related to storas-app

This is how to make a private repository on GitHub:
https://lmgtfy.com/?q=how+to+make+github+repository+private

**Comment by christianmahardhika** [comment]
Mas kalo mau host mbok ya diprivate reponya. capek2 saya bikinnya malah diumbar2 api key nya

**Comment by EggyBond** [comment]
Oh iya sorry mas, ini sudah saya private
